version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"  # Пробрасываем порт Vue.js приложения

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "1337:1337"  # Пробрасываем порт Strapi приложения

    # Здесь вы также можете указать другие настройки, например, переменные окружения для бэкенда Strapi
